#Requires -Version 5.1
Set-StrictMode -Version Latest

function Read-DotEnvFile {
    param([string] $Path)

    $values = [ordered]@{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $values
    }

    foreach ($line in Get-Content -LiteralPath $Path) {
        $trimmed = $line.Trim()
        if ($trimmed.Length -eq 0 -or $trimmed.StartsWith('#')) {
            continue
        }

        $separatorIndex = $trimmed.IndexOf('=')
        if ($separatorIndex -le 0) {
            continue
        }

        $key = $trimmed.Substring(0, $separatorIndex).Trim()
        $value = $trimmed.Substring($separatorIndex + 1).Trim()
        if ($value.Length -ge 2) {
            if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
                $value = $value.Substring(1, $value.Length - 2)
            }
        }

        $values[$key] = $value
    }

    return $values
}

function Get-DefaultEnvValues {
    [ordered]@{
        TELEGRAM_BOT_TOKEN = ''
        TELEGRAM_CHAT_ID = ''
        CLAUDE_API_KEY = ''
        ANTHROPIC_API_KEY = ''
        CLAUDE_MODEL = 'claude-haiku-4-5-20251001'
        CLAUDE_ENABLED = 'true'
        CLAUDE_TIMEOUT_SECONDS = '60'
        CLAUDE_MAX_RETRIES = '1'
        MIN_CONFIDENCE_TO_NOTIFY = '70'
        SEND_IGNORED_SIGNALS = 'false'
        PAPER_TRADING_ENABLED = 'true'
        DEFAULT_POSITION_QUANTITY = '1'
        ALLOW_TEST_TRADES = 'false'
        SEND_TEST_TELEGRAM = 'false'
        MARKET_PROVIDER = 'NASDAQ'
        MARKET_TIMEZONE = 'America/New_York'
        ENABLE_24_5_TRADING = 'true'
        ALLOW_PREMARKET = 'true'
        ALLOW_AFTER_HOURS = 'true'
        ALLOW_OVERNIGHT = 'true'
        IGNORE_SIGNALS_WHEN_MARKET_CLOSED = 'true'
        SEND_MARKET_CLOSED_NOTIFICATIONS = 'false'
        MIN_CONFIDENCE_REGULAR = '60'
        MIN_CONFIDENCE_PREMARKET = '70'
        MIN_CONFIDENCE_AFTER_HOURS = '70'
        MIN_CONFIDENCE_OVERNIGHT = '75'
        MAX_PRICE_DRIFT_PERCENT_REGULAR = '1.0'
        MAX_PRICE_DRIFT_PERCENT_EXTENDED = '2.5'
        SEND_WAIT_SIGNALS = 'false'
        ALLOW_SCALE_IN = 'false'
        MAX_POSITIONS_PER_SYMBOL = '1'
        SEND_DUPLICATE_BUY_NOTIFICATIONS = 'false'
        DATABASE_PATH = '/app/data/tradingagent.db'
        RETENTION_DAYS = '30'
        WEBHOOK_SECRET = 'darko123'
        ASPNETCORE_URLS = 'http://+:8080'
    }
}

function New-DeploymentEnvContent {
    param(
        [string] $DevEnvPath,
        [switch] $ExampleOnly
    )

    $defaults = Get-DefaultEnvValues
    $devValues = Read-DotEnvFile -Path $DevEnvPath
    $secretKeys = @('TELEGRAM_BOT_TOKEN', 'TELEGRAM_CHAT_ID', 'CLAUDE_API_KEY', 'ANTHROPIC_API_KEY')

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('# TradingAgent environment configuration')
    $lines.Add('# Generated by build-deployment-package.ps1')
    $lines.Add('')

    foreach ($entry in $defaults.GetEnumerator()) {
        $key = [string]$entry.Key
        $value = [string]$entry.Value

        if ($devValues.Contains($key) -and $devValues[$key]) {
            $value = [string]$devValues[$key]
        }

        if ($ExampleOnly -or ($secretKeys -contains $key)) {
            $value = ''
        }

        $lines.Add("$key=$value")
    }

    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function New-DeploymentDockerCompose {
    return @'
services:
  tradingagent:
    image: tradingagent:latest
    container_name: tradingagent-app
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: tradingagent-nginx
    depends_on:
      - tradingagent
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
'@
}

function New-DeploymentReadme {
    param([string] $BuildTimestamp)

    return @"
# TradingAgent Deployment Package

Generated: $BuildTimestamp

This package runs on **Windows with Docker Desktop only**. No Visual Studio or .NET SDK is required on the target machine.

## Contents

| File | Purpose |
|------|---------|
| ``tradingagent-image.tar`` | Pre-built Docker image |
| ``docker-compose.yml`` | Application + Nginx stack |
| ``nginx.conf`` | Reverse proxy configuration |
| ``.env`` | Ready-to-run configuration (add API keys) |
| ``.env.example`` | Template with empty secrets |
| ``start.ps1`` | Start the stack |
| ``stop.ps1`` | Stop the stack |
| ``restart.ps1`` | Restart the stack |
| ``status.ps1`` | Show runtime status |
| ``logs.ps1`` | Follow container logs |
| ``backup-db.ps1`` | Backup SQLite database |
| ``restore-db.ps1`` | Restore database from backup |
| ``update-image.ps1`` | Load updated image tar and restart |
| ``clean.ps1`` | Prune unused Docker resources |
| ``healthcheck.ps1`` | Validate deployment health |

## Installation

1. Install [Docker Desktop for Windows](https://www.docker.com/products/docker-desktop/)
2. Extract this deployment package to a folder, e.g. ``C:\TradingAgent``
3. Open PowerShell in that folder
4. Edit ``.env`` and add your API keys:
   - ``CLAUDE_API_KEY`` or ``ANTHROPIC_API_KEY``
   - ``TELEGRAM_BOT_TOKEN`` and ``TELEGRAM_CHAT_ID`` (optional)
5. Run:

``````powershell
.\start.ps1
``````

## URLs

| Service | URL |
|---------|-----|
| Dashboard | http://localhost:8085/ |
| API settings | http://localhost:8085/api/settings |
| Market status | http://localhost:8085/api/market/status |
| TradingView webhook | http://localhost:8085/api/tradingview/webhook |
| Test webhook | http://localhost:8085/api/test-webhook |

> OpenAPI/Swagger is not included. Use the dashboard and ``/api/*`` diagnostic endpoints.

## Start / Stop / Restart

``````powershell
.\start.ps1
.\stop.ps1
.\restart.ps1
``````

## Update

Replace ``tradingagent-image.tar`` with a newer export, then:

``````powershell
.\update-image.ps1
``````

## Backup and restore

``````powershell
.\backup-db.ps1
.\restore-db.ps1
``````

Backups are stored in ``backups\``.

## Logs

``````powershell
.\logs.ps1
``````

## Health check

``````powershell
.\healthcheck.ps1
``````

## TradingView setup

1. Create an alert in TradingView
2. Set webhook URL to: ``http://<your-server-ip>:8085/api/tradingview/webhook``
3. Use JSON body with ``symbol``, ``signal``, and ``secret`` matching ``WEBHOOK_SECRET`` in ``.env``
4. Use **string** values for ``price`` and ``rsi`` (not raw numbers)

Example payload:

``````json
{
  "symbol": "NVDA",
  "signal": "BUY",
  "price": "199.20",
  "timeframe": "1H",
  "strategy": "EMA_RSI",
  "secret": "your-webhook-secret"
}
``````

## Telegram setup

1. Create a bot via [@BotFather](https://t.me/BotFather)
2. Start a chat with the bot and send a message
3. Open ``https://api.telegram.org/bot<TOKEN>/getUpdates`` to find ``chat.id``
4. Set ``TELEGRAM_BOT_TOKEN`` and ``TELEGRAM_CHAT_ID`` in ``.env``
5. Run ``.\restart.ps1``

## Claude setup

1. Create an Anthropic API key
2. Set ``CLAUDE_API_KEY`` in ``.env``
3. Set ``CLAUDE_ENABLED=true``
4. Run ``.\restart.ps1``

## Yahoo Finance

Market data is fetched automatically at runtime. Test with:

``````powershell
Invoke-RestMethod http://localhost:8085/api/test-yahoo
``````

## Troubleshooting

| Issue | Fix |
|-------|-----|
| Docker not running | Start Docker Desktop and wait until it is ready |
| Port 8085 in use | Change ``8085:80`` in ``docker-compose.yml`` |
| Webhook 400 Invalid JSON | Send ``price``/``rsi`` as strings in JSON body |
| Webhook 401 | Check ``WEBHOOK_SECRET`` matches payload/header |
| Market closed signals ignored | Expected on weekends/holidays; see ``ENABLE_24_5_TRADING`` |
| Database missing | Run ``.\start.ps1`` — creates ``data\`` automatically |

## Data locations

| Path | Description |
|------|-------------|
| ``.\data\tradingagent.db`` | SQLite database (bind-mounted into container) |
| ``.\backups\`` | Database backups |
| ``.\logs\`` | Reserved for future log exports |

"@
}

function New-DeployStartScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

function Write-Info([string]$Message) { Write-Host $Message -ForegroundColor Cyan }
function Write-Ok([string]$Message) { Write-Host $Message -ForegroundColor Green }
function Write-Warn([string]$Message) { Write-Host $Message -ForegroundColor Yellow }

Write-Info 'Checking Docker Desktop...'
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw 'Docker is not installed. Install Docker Desktop for Windows first.'
}

docker info *> $null
if ($LASTEXITCODE -ne 0) {
    throw 'Docker engine is not running. Start Docker Desktop and try again.'
}
Write-Ok 'Docker engine is running.'

$imageName = 'tradingagent:latest'
$imageExists = docker image inspect $imageName *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Info 'Docker image not found locally. Loading tradingagent-image.tar...'
    if (-not (Test-Path -LiteralPath '.\tradingagent-image.tar')) {
        throw 'tradingagent-image.tar not found in deployment folder.'
    }
    docker load -i .\tradingagent-image.tar
    if ($LASTEXITCODE -ne 0) { throw 'docker load failed.' }
    Write-Ok 'Docker image loaded.'
} else {
    Write-Ok 'Docker image already present.'
}

foreach ($folder in @('data', 'logs', 'backups')) {
    if (-not (Test-Path -LiteralPath $folder)) {
        New-Item -ItemType Directory -Path $folder | Out-Null
        Write-Ok "Created folder: $folder"
    }
}

if (-not (Test-Path -LiteralPath '.\.env')) {
    if (Test-Path -LiteralPath '.\.env.example') {
        Copy-Item -LiteralPath '.\.env.example' -Destination '.\.env'
        Write-Warn '.env was missing — copied from .env.example. Edit API keys before production use.'
    } else {
        throw '.env file is missing.'
    }
}

Write-Info 'Starting containers...'
docker compose --env-file .env up -d
if ($LASTEXITCODE -ne 0) { throw 'docker compose up failed.' }

Write-Info 'Waiting for application to become healthy...'
$healthy = $false
for ($attempt = 1; $attempt -le 45; $attempt++) {
    try {
        $response = Invoke-WebRequest -Uri 'http://localhost:8085/api/market/status' -UseBasicParsing -TimeoutSec 5
        if ($response.StatusCode -eq 200) {
            $healthy = $true
            break
        }
    } catch {
        Start-Sleep -Seconds 2
    }
}

if (-not $healthy) {
    Write-Warn 'Application did not respond in time. Check logs with .\logs.ps1'
} else {
    Write-Ok 'Application is healthy.'
}

$imageId = (docker image inspect tradingagent:latest --format '{{.Id}}' 2>$null)
$shortId = if ($imageId) { $imageId.Substring(7, [Math]::Min(12, $imageId.Length - 7)) } else { 'unknown' }

Write-Host ''
Write-Ok 'TradingAgent started successfully.'
Write-Host 'Dashboard URL : http://localhost:8085/'
Write-Host 'API reference : http://localhost:8085/api/settings'
Write-Host 'Webhook URL   : http://localhost:8085/api/tradingview/webhook'
Write-Host "Image version : $shortId"
Write-Host 'Database path : $((Resolve-Path .\data).Path)\tradingagent.db'
Write-Host ''
docker compose ps
'@
}

function New-DeployStopScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot
docker compose --env-file .env down
if ($LASTEXITCODE -ne 0) { throw 'docker compose down failed.' }
Write-Host 'TradingAgent stopped.' -ForegroundColor Green
'@
}

function New-DeployRestartScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot
docker compose --env-file .env down
if ($LASTEXITCODE -ne 0) { throw 'docker compose down failed.' }
docker compose --env-file .env up -d
if ($LASTEXITCODE -ne 0) { throw 'docker compose up failed.' }
Write-Host 'TradingAgent restarted.' -ForegroundColor Green
docker compose ps
'@
}

function New-DeployStatusScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

Write-Host '=== Container Status ===' -ForegroundColor Cyan
docker compose ps

$imageId = (docker image inspect tradingagent:latest --format '{{.Id}}' 2>$null)
$shortId = if ($imageId) { $imageId.Substring(7, [Math]::Min(12, $imageId.Length - 7)) } else { 'not loaded' }
Write-Host ''
Write-Host "Image version: $shortId"

$startedAt = docker inspect tradingagent-app --format '{{.State.StartedAt}}' 2>$null
if ($startedAt) {
    Write-Host "Container started: $startedAt"
    try {
        $start = [DateTime]::Parse($startedAt)
        $uptime = (Get-Date).ToUniversalTime() - $start.ToUniversalTime()
        Write-Host ("Uptime: {0}d {1}h {2}m" -f $uptime.Days, $uptime.Hours, $uptime.Minutes)
    } catch {}
}

Write-Host ''
Write-Host '=== Health ===' -ForegroundColor Cyan
try {
    $health = Invoke-RestMethod -Uri 'http://localhost:8085/api/market/status' -TimeoutSec 5
    Write-Host "API status: OK ($($health.marketSession))"
} catch {
    Write-Host "API status: UNREACHABLE ($($_.Exception.Message))" -ForegroundColor Yellow
}

Write-Host ''
Write-Host '=== Ports ===' -ForegroundColor Cyan
docker ps --filter name=tradingagent --format 'table {{.Names}}\t{{.Ports}}\t{{.Status}}'

Write-Host ''
Write-Host '=== Disk Usage ===' -ForegroundColor Cyan
docker system df

$dbPath = Join-Path (Get-Location) 'data\tradingagent.db'
if (Test-Path -LiteralPath $dbPath) {
  $size = (Get-Item -LiteralPath $dbPath).Length
  Write-Host ("Database file: {0:N2} MB" -f ($size / 1MB))
} else {
  Write-Host 'Database file: not created yet'
}
'@
}

function New-DeployLogsScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot
docker compose logs -f
'@
}

function New-DeployBackupDbScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

if (-not (Test-Path -LiteralPath '.\backups')) {
    New-Item -ItemType Directory -Path '.\backups' | Out-Null
}

$dbPath = '.\data\tradingagent.db'
if (-not (Test-Path -LiteralPath $dbPath)) {
    throw "Database not found at $dbPath. Start the application first."
}

$timestamp = Get-Date -Format 'yyyyMMdd_HHmm'
$backupPath = Join-Path '.\backups' "tradingagent_$timestamp.db"
Copy-Item -LiteralPath $dbPath -Destination $backupPath -Force
Write-Host "Backup created: $backupPath" -ForegroundColor Green
'@
}

function New-DeployRestoreDbScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

$backupDir = '.\backups'
if (-not (Test-Path -LiteralPath $backupDir)) {
    throw 'No backups folder found.'
}

$backups = Get-ChildItem -LiteralPath $backupDir -Filter 'tradingagent_*.db' | Sort-Object LastWriteTime -Descending
if ($backups.Count -eq 0) {
    throw 'No backup files found.'
}

Write-Host 'Available backups:' -ForegroundColor Cyan
for ($i = 0; $i -lt $backups.Count; $i++) {
    Write-Host ("[{0}] {1} ({2})" -f ($i + 1), $backups[$i].Name, $backups[$i].LastWriteTime)
}

$selection = Read-Host 'Select backup number'
$parsed = 0
if (-not [int]::TryParse($selection, [ref]$parsed)) {
    throw 'Invalid selection.'
}
$index = $parsed - 1
if ($index -lt 0 -or $index -ge $backups.Count) {
    throw 'Selection out of range.'
}

$confirm = Read-Host "Restore $($backups[$index].Name)? This will overwrite the current database. [Y/N]"
if ($confirm -notmatch '^[Yy]') {
    Write-Host 'Restore cancelled.'
    exit 0
}

if (-not (Test-Path -LiteralPath '.\data')) {
    New-Item -ItemType Directory -Path '.\data' | Out-Null
}

docker compose --env-file .env down | Out-Null
Copy-Item -LiteralPath $backups[$index].FullName -Destination '.\data\tradingagent.db' -Force
docker compose --env-file .env up -d
if ($LASTEXITCODE -ne 0) { throw 'Failed to restart containers after restore.' }
Write-Host 'Database restored and containers restarted.' -ForegroundColor Green
'@
}

function New-DeployUpdateImageScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

if (-not (Test-Path -LiteralPath '.\tradingagent-image.tar')) {
    throw 'tradingagent-image.tar not found.'
}

docker compose --env-file .env down
if ($LASTEXITCODE -ne 0) { throw 'docker compose down failed.' }

docker load -i .\tradingagent-image.tar
if ($LASTEXITCODE -ne 0) { throw 'docker load failed.' }

docker compose --env-file .env up -d
if ($LASTEXITCODE -ne 0) { throw 'docker compose up failed.' }

Write-Host 'Image updated and containers restarted.' -ForegroundColor Green
docker compose ps
'@
}

function New-DeployCleanScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

Write-Host 'This will remove unused Docker containers, images, and networks.' -ForegroundColor Yellow
Write-Host 'SQLite database and backups will NOT be deleted.' -ForegroundColor Green
$confirm = Read-Host 'Continue? [Y/N]'
if ($confirm -notmatch '^[Yy]') {
    Write-Host 'Clean cancelled.'
    exit 0
}

docker compose --env-file .env down 2>$null | Out-Null
docker system prune -f
if ($LASTEXITCODE -ne 0) { throw 'docker system prune failed.' }
Write-Host 'Docker cleanup completed.' -ForegroundColor Green
'@
}

function New-DeployHealthcheckScript {
    return @'
#Requires -Version 5.1
$ErrorActionPreference = 'Continue'
Set-Location $PSScriptRoot

$results = [ordered]@{}

function Test-Check {
    param([string]$Name, [scriptblock]$Action)
    try {
        & $Action
        $script:results[$Name] = 'PASS'
        Write-Host "[PASS] $Name" -ForegroundColor Green
    } catch {
        $script:results[$Name] = "FAIL: $($_.Exception.Message)"
        Write-Host "[FAIL] $Name - $($_.Exception.Message)" -ForegroundColor Red
    }
}

Test-Check 'Container running' {
    $running = @(docker ps --filter 'name=tradingagent' --format '{{.Names}}' 2>$null)
    if ($running.Count -eq 0 -or [string]::IsNullOrWhiteSpace($running[0])) {
        throw 'No running TradingAgent containers found.'
    }
}

Test-Check 'Database reachable' {
    $db = '.\data\tradingagent.db'
    if (-not (Test-Path -LiteralPath $db)) {
        throw 'Database file does not exist yet.'
    }
}

Test-Check 'Dashboard endpoint' {
    $response = Invoke-WebRequest -Uri 'http://localhost:8085/' -UseBasicParsing -TimeoutSec 10
    if ($response.StatusCode -ne 200) { throw "HTTP $($response.StatusCode)" }
}

Test-Check 'Market status API' {
    $response = Invoke-RestMethod -Uri 'http://localhost:8085/api/market/status' -TimeoutSec 10
    if (-not $response.marketSession) { throw 'Invalid market status response.' }
}

Test-Check 'Webhook endpoint' {
    $body = '{"symbol":"HEALTH","signal":"BUY","secret":"invalid"}'
    try {
        Invoke-WebRequest -Uri 'http://localhost:8085/api/tradingview/webhook' -Method POST -ContentType 'application/json' -Body $body -UseBasicParsing -TimeoutSec 10 | Out-Null
        throw 'Expected unauthorized response.'
    } catch {
        if ($_.Exception.Response.StatusCode.value__ -ne 401) {
            throw 'Webhook endpoint did not return expected 401 for invalid secret.'
        }
    }
}

Test-Check 'Claude configuration' {
    $settings = Invoke-RestMethod -Uri 'http://localhost:8085/api/settings' -TimeoutSec 10
    if ($settings.CLAUDE_ENABLED -and -not $settings.CLAUDE_MODEL) {
        throw 'Claude enabled but model not configured.'
    }
}

Test-Check 'Telegram configuration' {
    $settings = Invoke-RestMethod -Uri 'http://localhost:8085/api/settings' -TimeoutSec 10
    if ($settings -is [pscustomobject]) {
        Write-Host '  Telegram settings present (token/chat configured via .env).' -ForegroundColor DarkGray
    }
}

Test-Check 'Yahoo Finance reachable' {
    $yahoo = Invoke-RestMethod -Uri 'http://localhost:8085/api/test-yahoo' -TimeoutSec 30
    if (-not $yahoo.symbol) { throw 'Yahoo test response invalid.' }
}

Write-Host ''
$failed = @($results.GetEnumerator() | Where-Object { $_.Value -like 'FAIL*' })
if ($failed.Count -eq 0) {
    Write-Host 'HEALTH CHECK: PASS' -ForegroundColor Green
    exit 0
}

Write-Host 'HEALTH CHECK: FAIL' -ForegroundColor Red
foreach ($item in $failed) {
    Write-Host " - $($item.Key): $($item.Value)" -ForegroundColor Red
}
exit 1
'@
}

function Write-DeploymentPackageFiles {
    param(
        [string] $DeployDir,
        [string] $DevEnvPath,
        [string] $NginxSource,
        [string] $BuildTimestamp
    )

    if (-not (Test-Path -LiteralPath $DeployDir)) {
        New-Item -ItemType Directory -Path $DeployDir | Out-Null
    }

    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    $files = [ordered]@{
        'docker-compose.yml' = New-DeploymentDockerCompose
        '.env' = New-DeploymentEnvContent -DevEnvPath $DevEnvPath
        '.env.example' = New-DeploymentEnvContent -DevEnvPath $DevEnvPath -ExampleOnly
        'README.md' = New-DeploymentReadme -BuildTimestamp $BuildTimestamp
        'start.ps1' = New-DeployStartScript
        'stop.ps1' = New-DeployStopScript
        'restart.ps1' = New-DeployRestartScript
        'status.ps1' = New-DeployStatusScript
        'logs.ps1' = New-DeployLogsScript
        'backup-db.ps1' = New-DeployBackupDbScript
        'restore-db.ps1' = New-DeployRestoreDbScript
        'update-image.ps1' = New-DeployUpdateImageScript
        'clean.ps1' = New-DeployCleanScript
        'healthcheck.ps1' = New-DeployHealthcheckScript
    }

    foreach ($entry in $files.GetEnumerator()) {
        $target = Join-Path $DeployDir $entry.Key
        [System.IO.File]::WriteAllText($target, $entry.Value, $utf8NoBom)
    }

    Copy-Item -LiteralPath $NginxSource -Destination (Join-Path $DeployDir 'nginx.conf') -Force
}

function Test-DeploymentPackage {
    param(
        [string] $DeployDir,
        [string] $ImageName
    )

    $required = @(
        'docker-compose.yml',
        '.env',
        '.env.example',
        'README.md',
        'nginx.conf',
        'tradingagent-image.tar',
        'start.ps1',
        'stop.ps1',
        'restart.ps1',
        'status.ps1',
        'logs.ps1',
        'clean.ps1',
        'backup-db.ps1',
        'restore-db.ps1',
        'update-image.ps1',
        'healthcheck.ps1'
    )

    $missing = @()
    foreach ($file in $required) {
        if (-not (Test-Path -LiteralPath (Join-Path $DeployDir $file))) {
            $missing += $file
        }
    }

    if ($missing.Count -gt 0) {
        throw "Deployment package is missing files: $($missing -join ', ')"
    }

    docker image inspect $ImageName | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker image '$ImageName' was not found after build."
    }

    $scriptErrors = @()
    foreach ($scriptName in $required | Where-Object { $_ -like '*.ps1' }) {
        $tokens = $null
        $errors = $null
        $null = [System.Management.Automation.Language.Parser]::ParseFile(
            (Join-Path $DeployDir $scriptName),
            [ref]$tokens,
            [ref]$errors)
        if ($errors.Count -gt 0) {
            $scriptErrors += "$scriptName : $($errors[0].Message)"
        }
    }

    if ($scriptErrors.Count -gt 0) {
        throw "Script validation failed:`n$($scriptErrors -join "`n")"
    }
}
